# Generated by Django 4.2.15 on 2024-08-30 07:33

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'menu.json')


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=25, verbose_name="Название"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Прямой URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="URL через reverse",
                        max_length=100,
                        null=True,
                        verbose_name="Именованный URL",
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(
                        max_length=25, verbose_name="Название меню"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.menuitem",
                        verbose_name="Родитель",
                    ),
                ),
            ],
        ),
        migrations.RunPython(load_fixture),
    ]
